project:
  type: website
  output-dir: docs

website:
  title: "Xiping Zhang's website"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



